### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by igoynawamreh**
- Update example: remove the image tab on parent and child page.
- Text changes.

### CODE REVIEW

**Review by taufik-nurrohman — COMMENTED** [review]
Actually, this is just an example. Everybody can use any method to detect which page they are currently in.

`0 === strpos($_['path'], 'page/gallery')` will also select `page/galleryfoobarbaz` while `'page/gallery' === $_['path']` will match exactly to the `page/gallery` string.

**Comment by taufik-nurrohman** [comment]
The easiest solution would be to extend the current path value with a boundary at the end so that we can match exactly to a path segments:

~~~ .php
$path = $_['path'] . '/';

if (0 === strpos($path, 'page/gallery/')) {
    // Will match `page/gallery` or `page/gallery/foobarbaz` but will not match `page/galleryfoobarbaz`
}
~~~

But it is not readable.

**Comment by igoynawamreh** [comment]
The image tab is still shown on `page/gallery` if using `'page/gallery' === $_['path'] || 0 === strpos($_['path'], 'page/gallery/')`?

**Comment by igoynawamreh** [comment]
> The image tab is still shown on `page/gallery`

Hidden on `page/gallery/child.page`, but still shown on `page/gallery.page`?

**Comment by taufik-nurrohman** [comment]
Then just use:

~~~ .php
if ('page/gallery' === Path::F($_['path'])) {}
~~~

To show only in `page/gallery` or `page/gallery.*` path.

~~~ .php
if (0 === strpos($_['path'], 'page/gallery/')) {}
~~~

To show only in `page/gallery/*` path.

**Comment by igoynawamreh** [comment]
Address: `localhost/panel/::g::/page/gallery.page`

```php
test('page/gallery' === Path::F($_['path'])); // false
test('page\\gallery' === Path::F($_['path'])); // true
```

**Comment by taufik-nurrohman** [comment]
> ~~~ .php
> test('page\\gallery' === Path::F($_['path'])); // true
> ~~~

Opps, sorry. It will happen only on Windows. You need to normalize the path separator by determining the second argument:

~~~ .php
Path::F($_['path'], '/');
~~~

**Comment by taufik-nurrohman** [comment]
I will merge this pull but may will change the IF statement later.

**Pull request merged**
